#!/bin/bash


#
##
####
####
####                              This is a bash script for installing Demonsaw Linux 
#### 
####
####       As of 9/08/2015, it is confirmed to work on both the x86_64 (64-bit) and i686 (32-bit) versions of the following Linux distros:
####
####            
####                |  Kali Linux 2.0  |  Ubuntu 14.04.3 LTS  |  Linux Mint 17.2 Rafaela  |   Elementary OS Freya 0.3.1  |
####
####	
####
####	
####
####
####  Before installing:    
####  ------------------
####	
####
####   !!!) IMPORTANT: Save this script as "install-demonsaw-linux" (without quotes).
####    
####    !!)  Make sure to apply "chmod +x install-demonsaw-linux" to the script before running.
####
####     !)  If you get any permission errors, trying running script as sudo.
####
####
####
####
####  After installing:
####  -----------------
####	
####	) Demonsaw will automatically start after installation.  
####	   To re-launch at any time, navigate to the 
####	   install directory and run "sudo ./demonsaw"
####
####	) Visit https://demonsaw.com/ and see the downloaded ~/demonsaw/README.TXT file for more information.
####		
####	) Look in https://www.reddit.com/r/demonsaw for extra stuff.
####
####
##
#


echo
echo
echo


mkdir -p ~/demonsaw
cp -f install-demonsaw-linux ~/demonsaw/install-demonsaw-linux
cd ~/demonsaw

echo
echo
echo

sleep 1

echo "Downloading files securely from demonsaw.com"

echo
echo
echo


#### Checks architecture and downloads appropriate .zip file from demonsaw.com.
###
##
#
#
if [[ $(uname -m) == 'x86_64' ]]; then
    echo "Downloading 64 Bit Version"
    echo "--------------------------"
    echo
    DL=$(curl -v --silent https://demonsaw.com/download.php 2>&1 | grep -m1 -A2 demonsaw_linux64.zip | cut -d'"' -f2 -s)
    curl -v --silent https://demonsaw.com/download.php 2>&1 | grep -m1 -A2 demonsaw_linux64.zip | cut -d'"' -f2 -s
    wget -N --https-only $DL
else
    echo "Downloading 32 Bit Version"
    echo "--------------------------"
    echo
    DL=$(curl -v --silent https://demonsaw.com/download.php 2>&1 | grep -m1 -A2 demonsaw_linux32.zip | cut -d'"' -f2 -s)
    wget -N --https-only $DL
fi

####  Checks to make sure the DL worked.
###
##
#
#
if [ $? -eq 0 ]; then
    DL=PASS
else
    DL=FAIL
fi


sleep 1


####  Creates a sha1sum formatted hash-check file as listed at https://demonsaw.com/download.php
###
##
#
#
if [[ $(uname -m) == 'x86_64' ]]; then
    SHA1=$(curl -v --silent https://demonsaw.com/download.php 2>&1 | grep -m1 -A2 demonsaw_linux64.zip | cut -d" " -f2 -s | cut -d"<" -f-1 | sed -n '2p')
    echo $SHA1 "demonsaw_linux64.zip" > demonsaw_linux64.zip.sha1
else
    SHA1=$(curl -v --silent https://demonsaw.com/download.php 2>&1 | grep -m1 -A2 demonsaw_linux32.zip | cut -d" " -f2 -s | cut -d"<" -f-1 | sed -n '2p')
    echo $SHA1 "demonsaw_linux32.zip" > demonsaw_linux32.zip.sha1
fi



echo
echo "--------------------------"
echo

echo "Verifying SHA-1 hash with sha1sum..."

echo
echo
echo


####  Confirmation of SHA-1 hash based on architecture being printed to screen.
###
##
#
#
if [[ $(uname -m) == 'x86_64' ]]; then
    echo "SHA-1= $SHA1"
else
    echo "SHA-1= $SHA1"
fi


echo
echo
echo

sleep 3


####  Runs sha1sum to compare the hashes of the downloaded zip files to the SHA-1 hashes listed at https://demonsaw.com/download.php
###
##
#
#
if [[ $(uname -m) == 'x86_64' ]]; then
    sha1sum --check --strict demonsaw_linux64.zip.sha1
else
    sha1sum --check --strict demonsaw_linux32.zip.sha1
fi



####  Confirms the results of sha1sum, and prints to screen.
###
##
#
#
if [ $? -eq 0 ]; then
    SHA1=PASS
    echo
    echo
    echo
    echo "The hash is valid.  To further verify, visit https://demonsaw.com/download.php."
    echo
else
    SHA1=FAIL
    echo
    echo
    echo
    echo "WARNING: The hash appears to be INVALID, please cancel installation and verify at https://demonsaw.com/download.php"
    echo
    echo
    echo
    exit
fi

sleep 3

echo
echo "--------------------------"
echo "Enter password in install."
echo "--------------------------"
echo



####  Installs the required libxcb packages to launch Demonsaw in the X Window System.
###
##
#
#
sudo apt-get update -y
sudo apt-get install -y mesa-common-dev libcr-dev libglu1-mesa-dev -y
sudo apt-get install -y libxcb1 libxcb1-dev libx11-xcb1 libx11-xcb-dev libxcb-keysyms1 libxcb-keysyms1-dev 
sudo apt-get install -y libxcb-image0 libxcb-image0-dev libxcb-shm0 libxcb-shm0-dev libxcb-icccm4 libxcb-icccm4-dev
sudo apt-get install -y libxcb-sync1 libxcb-sync0-dev libxcb-render-util0 libxcb-render-util0-dev libxcb-xfixes0-dev
sudo apt-get install -y libxrender-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-glx0-dev
sudo apt-get autoclean -y

echo
echo
echo


####  Creates a symbolic link between newer and older library files for redundancy.
###
##
#
#
if [[ $(uname -m) == 'x86_64' ]]; then    
    sudo ln -f -s /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 /usr/lib/x86_64-linux-gnu/libxcb-sync.so.0
    sudo ln -f -s /lib/x86_64-linux-gnu/libudev.so.1 /usr/lib/x86_64-linux-gnu/libudev.so.0	
    unzip -o demonsaw_linux64.zip
else
    sudo ln -f -s /usr/lib/i386-linux-gnu/libxcb-sync.so.1 /usr/lib/i386-linux-gnu/libxcb-sync.so.0
    sudo ln -f -s /lib/i386-linux-gnu/libudev.so.1 /usr/lib/i386-linux-gnu/libudev.so.0
    unzip -o demonsaw_linux32.zip
fi


echo
echo
echo


####  Checks to see if if the .zips downloaded, passed sha1sum, and unzipped,
####  adds execute privileges, and prints confirmation to screen.
###
##
#
#
exists=./demonsaw
if [ -f $exists ] && [ $DL = "PASS" ] && [ $SHA1 = "PASS" ]; then
    chmod +x demonsaw
    echo "The installation was successful."
else
    echo 
    echo "Installation failed."
    echo 
    exit
fi



echo 
echo
echo
echo 
echo
echo

####  Launches demonsaw.
###
##
#
#
sudo ./demonsaw

echo
echo
echo
####
##
#
